/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mlg.acciones.presentation.forms;

import com.mlg.acciones.helper.ApplicationConfig;
import com.mlg.acciones.vo.CompanyVo;
import com.mlg.acciones.vo.MarketVo;
import com.mlg.acciones.vo.QuoteVo;
import com.mlg.acciones.vo.StockVo;
import com.mlg.aciones.presentation.lists.model.ModeloLista;
import com.mlg.aciones.presentation.lists.render.CompanyListRenderer;
import com.mlg.aciones.presentation.lists.render.QuoteListRenderer;
import com.mlg.aciones.presentation.lists.render.StockListRenderer;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Owner
 */
public class ViewQuotes extends javax.swing.JPanel {
	
	AbstractListModel emptyMarketsListModel;
	AbstractListModel emptyCompaniesListModel;
	AbstractListModel emptyStocksListModel;
	AbstractListModel emptyQuotesListModel;
	AbstractListModel defaultCompaniesListModel;
	AbstractListModel defaultStocksListModel;
	AbstractListModel defaultQuotesListModel;
	ListCellRenderer defaultCellRenderer;

	/**
	 * Creates new form ViewQuotes
	 */
	public ViewQuotes() {
		emptyMarketsListModel = new javax.swing.AbstractListModel() {
			
			String[] strings = {"There are no markets available"};
			
			public int getSize() {
				return strings.length;
			}
			
			public Object getElementAt(int i) {
				return strings[i];
			}
		};
		emptyCompaniesListModel = new javax.swing.AbstractListModel() {
			
			String[] strings = {"There are no companies available for this market"};
			
			public int getSize() {
				return strings.length;
			}
			
			public Object getElementAt(int i) {
				return strings[i];
			}
		};
		emptyStocksListModel = new javax.swing.AbstractListModel() {
			
			String[] strings = {"There are no stocks available for this company"};
			
			public int getSize() {
				return strings.length;
			}
			
			public Object getElementAt(int i) {
				return strings[i];
			}
		};
		emptyQuotesListModel = new javax.swing.AbstractListModel() {
			
			String[] strings = {"There are no information available for this stock"};
			
			public int getSize() {
				return strings.length;
			}
			
			public Object getElementAt(int i) {
				return strings[i];
			}
		};
		defaultCompaniesListModel = new javax.swing.AbstractListModel() {
			
			String[] strings = {"Select a market"};
			
			public int getSize() {
				return strings.length;
			}
			
			public Object getElementAt(int i) {
				return strings[i];
			}
		};
		defaultStocksListModel = new javax.swing.AbstractListModel() {
			
			String[] strings = {"Select a company"};
			
			public int getSize() {
				return strings.length;
			}
			
			public Object getElementAt(int i) {
				return strings[i];
			}
		};
		defaultQuotesListModel = new javax.swing.AbstractListModel() {
			
			String[] strings = {"Select a stock"};
			
			public int getSize() {
				return strings.length;
			}
			
			public Object getElementAt(int i) {
				return strings[i];
			}
		};
		defaultCellRenderer = new DefaultListCellRenderer();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        marketList = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        companyList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        stockList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        marketDeleteButton = new javax.swing.JButton();
        marketCreateButton = new javax.swing.JButton();
        marketEditButton = new javax.swing.JButton();
        companyDeleteButton = new javax.swing.JButton();
        companyEditButton = new javax.swing.JButton();
        companyCreateButton = new javax.swing.JButton();
        stockCreateButton = new javax.swing.JButton();
        stockEditButton = new javax.swing.JButton();
        stockDeleteButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        quoteList = new javax.swing.JList();
        quoteCreateButton = new javax.swing.JButton();
        quoteEditButton = new javax.swing.JButton();
        quoteDeleteButton = new javax.swing.JButton();

        List<MarketVo> availableMarkets = ApplicationConfig.getInstance().getFacadeFactory().getMarketFacade().getAll();
        AbstractListModel marketsListModel;
        if(availableMarkets.isEmpty()){
            marketsListModel = emptyMarketsListModel;
        }else{
            marketsListModel = new ModeloLista<MarketVo>(availableMarkets);
        }
        marketList.setModel(marketsListModel
        );
        marketList.setCellRenderer(new CompanyListRenderer());
        marketList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marketListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(marketList);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        companyList.setModel(defaultCompaniesListModel
        );
        companyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(companyList);

        jLabel1.setText("Select a market");

        jLabel2.setText("Select a company");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        stockList.setModel(defaultStocksListModel);
        stockList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(stockList);

        jLabel3.setText("Select a stock");

        marketDeleteButton.setText("Delete market");
        marketDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketDeleteButtonActionPerformed(evt);
            }
        });

        marketCreateButton.setText("Create market");
        marketCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketCreateButtonActionPerformed(evt);
            }
        });

        marketEditButton.setLabel("Edit market");
        marketEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketEditButtonActionPerformed(evt);
            }
        });

        companyDeleteButton.setText("Delete company");
        companyDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyDeleteButtonActionPerformed(evt);
            }
        });

        companyEditButton.setText("Edit company");
        companyEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyEditButtonActionPerformed(evt);
            }
        });

        companyCreateButton.setText("Create company");
        companyCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyCreateButtonActionPerformed(evt);
            }
        });

        stockCreateButton.setText("Create stock");
        stockCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockCreateButtonActionPerformed(evt);
            }
        });

        stockEditButton.setText("Edit stock");
        stockEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockEditButtonActionPerformed(evt);
            }
        });

        stockDeleteButton.setText("Delete stock");
        stockDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockDeleteButtonActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("Select a quote");

        quoteList.setModel(defaultQuotesListModel);
        jScrollPane4.setViewportView(quoteList);

        quoteCreateButton.setText("Create stock");
        quoteCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quoteCreateButtonActionPerformed(evt);
            }
        });

        quoteEditButton.setText("Edit quote");
        quoteEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quoteEditButtonActionPerformed(evt);
            }
        });

        quoteDeleteButton.setText("Delete quote");
        quoteDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quoteDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(marketCreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(marketEditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marketDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(companyDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(companyCreateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(companyEditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(stockCreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(stockEditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(quoteCreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(quoteDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(quoteEditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(marketCreateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(marketEditButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(marketDeleteButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(companyCreateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(companyEditButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(companyDeleteButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(stockCreateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stockEditButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stockDeleteButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quoteCreateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quoteEditButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quoteDeleteButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void marketDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketDeleteButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_marketDeleteButtonActionPerformed
	
    private void marketCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketCreateButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_marketCreateButtonActionPerformed
	
    private void marketEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketEditButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_marketEditButtonActionPerformed
	
    private void companyDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyDeleteButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_companyDeleteButtonActionPerformed
	
    private void companyEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyEditButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_companyEditButtonActionPerformed
	
    private void companyCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyCreateButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_companyCreateButtonActionPerformed
	
    private void stockCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockCreateButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_stockCreateButtonActionPerformed
	
    private void stockEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockEditButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_stockEditButtonActionPerformed
	
    private void stockDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockDeleteButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_stockDeleteButtonActionPerformed
	
    private void quoteCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quoteCreateButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_quoteCreateButtonActionPerformed
	
    private void quoteEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quoteEditButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_quoteEditButtonActionPerformed
	
    private void quoteDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quoteDeleteButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_quoteDeleteButtonActionPerformed
	
	private void marketListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marketListMouseClicked
		if (evt.getClickCount() == 2) {
			MarketVo market = (MarketVo) marketList.getSelectedValue();
			setCompanyList(market);
		}
	}//GEN-LAST:event_marketListMouseClicked
	
	private void companyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyListMouseClicked
		if (evt.getClickCount() == 2) {
			CompanyVo company = (CompanyVo) companyList.getSelectedValue();
			setStockList(company);
		}
	}//GEN-LAST:event_companyListMouseClicked
	
	private void stockListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockListMouseClicked
		if (evt.getClickCount() == 2) {
			StockVo stock = (StockVo) stockList.getSelectedValue();
			setQuoteList(stock);
		}
	}//GEN-LAST:event_stockListMouseClicked
	
	private void setQuoteList(StockVo stock) {
		List<QuoteVo> quotes = ApplicationConfig.getInstance().getFacadeFactory().getQuoteFacade().getAll(stock.getId());
		if (quotes.isEmpty()) {
			quoteList.setCellRenderer(defaultCellRenderer);
			quoteList.setModel(emptyQuotesListModel);
		} else {
			quoteList.setCellRenderer(new QuoteListRenderer());
			quoteList.setModel(new ModeloLista<QuoteVo>(quotes));
		}
	}

	private void setStockList(CompanyVo company) {
		List<StockVo> stocks = ApplicationConfig.getInstance().getFacadeFactory().getStockFacade().getAll(company.getId());
		if (stocks.isEmpty()) {
			stockList.setModel(emptyStocksListModel);
			stockList.setCellRenderer(defaultCellRenderer);
		} else {
			stockList.setCellRenderer(new StockListRenderer());
			stockList.setModel(new ModeloLista<StockVo>(stocks));
		}
		clearDownStock();
	}
	
	private void setCompanyList(MarketVo market) {
		List<CompanyVo> companies = ApplicationConfig.getInstance().getFacadeFactory().getCompanyFacade().getAll(market.getId());
		if (companies.isEmpty()) {
			companyList.setModel(emptyCompaniesListModel);
			companyList.setCellRenderer(defaultCellRenderer);
		} else {
			companyList.setCellRenderer(new CompanyListRenderer());
			companyList.setModel(new ModeloLista<CompanyVo>(companies));
		}
		//Clear lists down company
		clearDownCompany();
	}
	
	private void clearMarket() {
		marketList.setCellRenderer(defaultCellRenderer);
		marketList.setModel(emptyMarketsListModel);
		clearDownMarket();
	}
	
	private void clearCompany() {
		clearDownMarket();
	}
	
	private void clearStock() {
		clearDownCompany();
	}
	
	private void clearQuote() {
		quoteList.setCellRenderer(defaultCellRenderer);
		quoteList.setModel(emptyQuotesListModel);
	}

	private void clearDownMarket() {
		companyList.setCellRenderer(defaultCellRenderer);
		companyList.setModel(defaultCompaniesListModel);
		clearDownCompany();
	}
	
	private void clearDownCompany() {
		stockList.setCellRenderer(defaultCellRenderer);
		stockList.setModel(defaultStocksListModel);
		clearDownStock();
	}
	
	private void clearDownStock() {
		quoteList.setCellRenderer(defaultCellRenderer);
		quoteList.setModel(defaultQuotesListModel);
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton companyCreateButton;
    private javax.swing.JButton companyDeleteButton;
    private javax.swing.JButton companyEditButton;
    private javax.swing.JList companyList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton marketCreateButton;
    private javax.swing.JButton marketDeleteButton;
    private javax.swing.JButton marketEditButton;
    private javax.swing.JList marketList;
    private javax.swing.JButton quoteCreateButton;
    private javax.swing.JButton quoteDeleteButton;
    private javax.swing.JButton quoteEditButton;
    private javax.swing.JList quoteList;
    private javax.swing.JButton stockCreateButton;
    private javax.swing.JButton stockDeleteButton;
    private javax.swing.JButton stockEditButton;
    private javax.swing.JList stockList;
    // End of variables declaration//GEN-END:variables
}
